services:
  location:
    build: ./location-service
    ports:
      - "8091:5000"
  pet:
    build: ./pet-service
    ports:
      - "8092:5000"
  user:
    build: ./user-service
    ports:
      - "8093:5000"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"   # ถ้า frontend ใช้ nginx serve build แล้ว
    depends_on:
      - location
      - pet
      - user
