version: '3.9'

services:
  frontend:
    image: it66070178/frontend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8090:80"
    networks:
      - express-network

  user:
    image: it66070178/user:latest
    networks:
      - express-network

  pet:
    image: it66070178/pet:latest
    networks:
      - express-network

  location:
    image: it66070178/location:latest
    networks:
      - express-network

networks:
  express-network:
    driver: bridge
