version: '3.9'

services:
  frontend:
    image: it66070178/frontend:latest
    # ใช้ dynamic port mapping เพื่อให้หลาย container ไม่ชนกัน
    ports:
      - "8090-8095:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - express-network

  user:
    image: it66070178/user:latest
    networks:
      - express-network

  pet:
    image: it66070178/pet:latest
    networks:
      - express-network

  location:
    image: it66070178/location:latest
    networks:
      - express-network

networks:
  express-network:
    driver: bridge
