version: '3.9'

services:
  frontend:
    image: it66070178/frontend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      # published port สำหรับ Swarm load balancing
      ports:
        - target: 80
          published: 8090
          protocol: tcp
          mode: host
    networks:
      - express-network

  user:
    image: it66070178/user:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - express-network

  pet:
    image: it66070178/pet:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - express-network

  location:
    image: it66070178/location:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - express-network

networks:
  express-network:
    driver: overlay
