version: '3.9'

services:
  frontend1:
    image: it66070178/frontend:latest
    networks:
      - express-network

  frontend2:
    image: it66070178/frontend:latest
    networks:
      - express-network

  user1:
    image: it66070178/user:latest
    networks:
      - express-network

  user2:
    image: it66070178/user:latest
    networks:
      - express-network

  pet1:
    image: it66070178/pet:latest
    networks:
      - express-network

  pet2:
    image: it66070178/pet:latest
    networks:
      - express-network

  location1:
    image: it66070178/location:latest
    networks:
      - express-network

  location2:
    image: it66070178/location:latest
    networks:
      - express-network

  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - express-network
    depends_on:
      - frontend1
      - frontend2
      - user1
      - user2
      - pet1
      - pet2
      - location1
      - location2

networks:
  express-network:
    driver: bridge
