version: '3.9'

services:
  frontend1:
    image: it66070178/frontend:latest
    networks:
      - petnet

  frontend2:
    image: it66070178/frontend:latest
    networks:
      - petnet

  user1:
    image: it66070178/user:latest
    networks:
      - petnet

  user2:
    image: it66070178/user:latest
    networks:
      - petnet

  pet1:
    image: it66070178/pet:latest
    networks:
      - petnet

  pet2:
    image: it66070178/pet:latest
    networks:
      - petnet

  location1:
    image: it66070178/location:latest
    networks:
      - petnet
    environment:
      NGROK_AUTHTOKEN: "33z87GRfa18fZk0r06WNmQ0MOqX_6AZfGX92wv7WSjhink45N"

  location2:
    image: it66070178/location:latest
    networks:
      - petnet
    environment:
      NGROK_AUTHTOKEN: "33z87GRfa18fZk0r06WNmQ0MOqX_6AZfGX92wv7WSjhink45N"

  nginx:
    image: nginx:latest
    container_name: pettrack_nginx_c
    ports:
      - "8091:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - petnet
    depends_on:
      - frontend1
      - frontend2
      - user1
      - user2
      - pet1
      - pet2
      - location1
      - location2

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter_c
    environment:
      - NGINX_SCRAPE_URI=http://nginx:80/nginx_status
    networks
