version: '3.9'

services:
  frontend:
    image: it66070178/frontend:latest
    ports:
      - "8090:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  location:
    image: it66070178/location:latest
    deploy:
      replicas: 2

  pet:
    image: it66070178/pet:latest
    deploy:
      replicas: 2

  user:
    image: it66070178/user:latest
    deploy:
      replicas: 2

networks:
  default:
    name: express-network
