global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-pet-service'
    static_configs:
      - targets: ['user-pet-service:3000']

  - job_name: 'location-service'
    static_configs:
      - targets: ['location-service:5000']

  # --- เพิ่ม 2 job นี้เข้ามา ---
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
